### ISSUE TITLE
can I run angular2 without node

### ISSUE THREAD

**Issue by mdimp** [planetoftheweb/angular2#3]
I want to write angular2 with html without node.

**Comment by planetoftheweb** [comment]
The gulp process I have built just automates things. You do need to have something that processes the TypeScript so you need something like a gulp process or an NodeJS process to handle that. The processed files do not require NodeJS.

**Comment by zeronil** [comment]
If you want to write Angular 2 code with ECMAScript 5 instead of TypeScript, there's a really good course on Udemy that will get you started. It shows how to build a simple app using ECMAScript 5, ECMAScript 2015, and TypeScript (it's the same app built using each technology). The rest of the course is focused on TypeScript, but it may help you understand the basics of writing an Angular 2 application if you want to avoid using a transpiler. https://www.udemy.com/angular-2-from-the-ground-up/

**Comment by planetoftheweb** [comment]
If you're serious about Angular 2, you'll want to learn how to do things with TypeScript and ES6, anything else is frankly a waste of time. Originally I was going to make my course cover ES5 Angular 2, but the documentation for it is weak, and using decorations makes it so much easier to do things with Angular. You can read about it in my blog post. http://www.raybo.org/blog/2016/02/18/AngularJS-2_what_to_look_for_when_migrating_to_the_new_version.html.
